### ISSUE TITLE
Create agents based on parsed sample json file

### ISSUE THREAD

**Issue by Sushant-Chavan** [HBRS-MAAS/ws18-project-commitment_issues#24]
This is a followup of Issue #19 . Must be started only after #19 is completed

**Comment by AbanoubAbdelmalak** [comment]
Updating the issue according to #26 

Agents to be created:
* Customer
* OrderProcessor
* Proofer
* CoolingRack
* LoadingBay
* MailBox

**Comment by AhmedFaisal95** [comment]
Fixed with pull request #40
