### ISSUE TITLE
Generating required agents for sample scenarios

### ISSUE THREAD

**Issue by Sushant-Chavan** [HBRS-MAAS/ws18-project-commitment_issues#26]
Hi Argentina,
Could you please clarify if we need to implement just the orderProcessor and Customer agents based on the parsed json files, or we need to implement all the agents that can be based on the json file(for example the baking agents)

**Comment by argenos** [comment]
At the very least, all order processing agents and the agents which will act as interfaces between stages

**Comment by AbanoubAbdelmalak** [comment]
@argenos Thanks for the clarification
