### ISSUE TITLE
Implement OrderAggregator

### ISSUE THREAD

**Issue by Sushant-Chavan** [HBRS-MAAS/ws18-project-commitment_issues#44]
- [x] Parse the message received from the loading bay agent
- [x] Check order fulfillment
- [x] Inform the Transport agent once an order is fulfilled with a message containing the list of boxes for the order

**Comment by Sushant-Chavan** [comment]
Waiting for the output message format of the LoadingBay interface agent.

**Comment by AbanoubAbdelmalak** [comment]
Solved with pull request #72
