### ISSUE TITLE
Implement TransportAgent

### ISSUE THREAD

**Issue by Sushant-Chavan** [HBRS-MAAS/ws18-project-commitment_issues#45]
- [x] Parse the message from OrderAggregator
- [x] Call for proposal to deliver orders from the trucks and choose the best truck for delivery
- [x] Inform the trucks of the list of boxes and the customer location for an order

**Comment by AbanoubAbdelmalak** [comment]
This issue is almost done but still a little dependent on the order aggregator #44 .

**Comment by AbanoubAbdelmalak** [comment]
solved by pull request #56
