### ISSUE TITLE
Implement MailboxAgent

### ISSUE THREAD

**Issue by Sushant-Chavan** [HBRS-MAAS/ws18-project-commitment_issues#48]
- [x] Parse the message received from TruckAgent
- [x] Inform all interested agents about the completion of a customer order
- [x] Create a pull request to the upstream

**Comment by Sushant-Chavan** [comment]
Waiting for the BaseAgent to be merged in the upstream.

**Comment by AhmedFaisal95** [comment]
Resolved with #52
