### ISSUE TITLE
Modify LoadingBay Agent to to fit architecture updates

### ISSUE THREAD

**Issue by Sushant-Chavan** [HBRS-MAAS/ws18-project-commitment_issues#69]
Updating the LoadingBay agent to ensure that all the items of a certain product in a certain order arrive before passing the boxes over to the delivery stage. This change is required to enable integration with the packaging phase.

Must accomplish the following:
- [x] Receive a message containing boxes of products relating to a particular order and parsing it
- [x] Maintain a database of the products and their quantities received for each customer order ID
- [x] Receive messages of all order and all their details (from the OrderProcessor)
- [x]  Cross check orders and received boxes: For each order's boxes, should not send over to delivery until all products have arrived.

**Comment by AhmedFaisal95** [comment]
Resolved with pull request #78
